In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [8]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int32


In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
x = np.array([10,20,30,40])
x > 20

array([False, False,  True,  True])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [17]:
arr = np.array([10,20,30,40,50])

In [18]:
arr[-1]

50

In [24]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a*b

print(c*a)

[ 1  8 27]


In [31]:
z = [[1,2],[2,3],[3,4]]
y = np.array(z)
x = np.array(list(range(10)))
print(z)
print(y)
print(x)

[[1, 2], [2, 3], [3, 4]]
[[1 2]
 [2 3]
 [3 4]]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
y.reshape(2,3)
y.reshape(3,2)

array([[1, 2],
       [2, 3],
       [3, 4]])